# yamllint disable rule:line-length
---
parameters:
  xima_typo3_content_audit.widgets.daily_mission.options:
    refreshAvailable: true
  xima_typo3_content_audit.widgets.stale_pages.options:
    refreshAvailable: true
    excludePageUids: []
  xima_typo3_content_audit.widgets.fresh_pages.options:
    refreshAvailable: true
    excludePageUids: []
  xima_typo3_content_audit.widgets.hidden_pages.options:
    refreshAvailable: true
    excludePageUids: []
  xima_typo3_content_audit.widgets.hidden_content.options:
    refreshAvailable: true
    excludePageUids: []
  xima_typo3_content_audit.widgets.empty_pages.options:
    refreshAvailable: true
    excludePageUids: []
    allowedPageTypes: [1]
  xima_typo3_content_audit.widgets.untranslated_pages.options:
    refreshAvailable: true
    excludePageUids: []
  xima_typo3_content_audit.widgets.missing_page_fields.options:
    refreshAvailable: true
    missingField: 'abstract'
    excludePageUids: []
  xima_typo3_content_audit.widgets.missing_image_fields.options:
    refreshAvailable: true
    missingField: 'alternative'
  xima_typo3_content_audit.widgets.broken_links.options:
    refreshAvailable: true
  xima_typo3_content_audit.widgets.recent_changes.options:
    refreshAvailable: true
    excludePageUids: []
  xima_typo3_content_audit.widgets.content_statistics.options:
    refreshAvailable: true

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Xima\XimaTypo3ContentAudit\:
    resource: '../Classes/*'

  Xima\XimaTypo3ContentAudit\EventListener\BackendAssetsListener:
    tags:
      - name: event.listener
        identifier: 'xima-typo3-content-audit/backend-assets'
        event: 'TYPO3\CMS\Backend\Controller\Event\AfterBackendPageRenderEvent'

  # @todo Simplify event handling once support for TYPO3 12/13 is dropped
  Xima\XimaTypo3ContentAudit\EventListener\PageTreeFilterListener:
    arguments:
      $stalePagesOptions: '%xima_typo3_content_audit.widgets.stale_pages.options%'
      $freshPagesOptions: '%xima_typo3_content_audit.widgets.fresh_pages.options%'
      $hiddenPagesOptions: '%xima_typo3_content_audit.widgets.hidden_pages.options%'
      $hiddenContentOptions: '%xima_typo3_content_audit.widgets.hidden_content.options%'
      $emptyPagesOptions: '%xima_typo3_content_audit.widgets.empty_pages.options%'
      $untranslatedPagesOptions: '%xima_typo3_content_audit.widgets.untranslated_pages.options%'
      $missingPageFieldsOptions: '%xima_typo3_content_audit.widgets.missing_page_fields.options%'
    tags:
      - name: event.listener
        identifier: 'xima-typo3-content-audit/pagetree-filter'
        event: 'TYPO3\CMS\Backend\Tree\Repository\BeforePageTreeIsFilteredEvent'
      - name: event.listener
        identifier: 'xima-typo3-content-audit/pagetree-filter-marker'
        event: 'TYPO3\CMS\Backend\Controller\Event\AfterPageTreeItemsPreparedEvent'
        method: 'markMatchedPages'

  Xima\XimaTypo3ContentAudit\Widgets\DailyMission:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\DailyMission'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\DailyMissionDataProvider'
      $options: '%xima_typo3_content_audit.widgets.daily_mission.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditDailyMission'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.daily_mission.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.daily_mission.description'
        iconIdentifier: 'content-audit-widgets-daily-mission'
        height: 'small'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\StalePages:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\StalePages'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\MergedPageChangeDataProvider'
      $options: '%xima_typo3_content_audit.widgets.stale_pages.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditStalePages'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.stale_pages.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.stale_pages.description'
        iconIdentifier: 'content-audit-widgets-stale-pages'
        height: 'large'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\FreshPages:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\FreshPages'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\MergedPageChangeDataProvider'
      $options: '%xima_typo3_content_audit.widgets.fresh_pages.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditFreshPages'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.fresh_pages.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.fresh_pages.description'
        iconIdentifier: 'content-audit-widgets-fresh-pages'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\HiddenPages:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\HiddenPages'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\HiddenPagesDataProvider'
      $options: '%xima_typo3_content_audit.widgets.hidden_pages.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditHiddenPages'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.hidden_pages.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.hidden_pages.description'
        iconIdentifier: 'content-audit-widgets-hidden-pages'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\HiddenContent:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\HiddenContent'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\HiddenContentDataProvider'
      $options: '%xima_typo3_content_audit.widgets.hidden_content.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditHiddenContent'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.hidden_content.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.hidden_content.description'
        iconIdentifier: 'content-audit-widgets-hidden-content'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\EmptyPages:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\EmptyPages'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\EmptyPagesDataProvider'
      $options: '%xima_typo3_content_audit.widgets.empty_pages.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditEmptyPages'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.empty_pages.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.empty_pages.description'
        iconIdentifier: 'content-audit-widgets-empty-pages'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\UntranslatedPages:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\UntranslatedPages'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\UntranslatedPagesDataProvider'
      $options: '%xima_typo3_content_audit.widgets.untranslated_pages.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditUntranslatedPages'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.untranslated_pages.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.untranslated_pages.description'
        iconIdentifier: 'content-audit-widgets-untranslated-pages'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\MissingPageFields:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\MissingPageFields'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\MissingPageFieldsDataProvider'
      $options: '%xima_typo3_content_audit.widgets.missing_page_fields.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditMissingPageFields'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.missing_page_fields.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.missing_page_fields.description'
        iconIdentifier: 'content-audit-widgets-missing-page-fields'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\MissingImageFields:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\MissingImageFields'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\MissingImageFieldsDataProvider'
      $options: '%xima_typo3_content_audit.widgets.missing_image_fields.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditMissingImageFields'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.missing_image_fields.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.missing_image_fields.description'
        iconIdentifier: 'content-audit-widgets-missing-image-fields'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\BrokenLinks:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\BrokenLinks'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\BrokenLinksDataProvider'
      $options: '%xima_typo3_content_audit.widgets.broken_links.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditBrokenLinks'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.broken_links.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.broken_links.description'
        iconIdentifier: 'content-audit-widgets-broken-links'
        height: 'medium'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\RecentChanges:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\RecentChanges'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\RecentChangesDataProvider'
      $options: '%xima_typo3_content_audit.widgets.recent_changes.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditRecentChanges'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.recent_changes.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.recent_changes.description'
        iconIdentifier: 'content-audit-widgets-recent-changes'
        height: 'large'
        width: 'medium'

  Xima\XimaTypo3ContentAudit\Widgets\ContentStatistics:
    class: 'Xima\XimaTypo3ContentAudit\Widgets\ContentStatistics'
    arguments:
      $backendViewFactory: '@TYPO3\CMS\Backend\View\BackendViewFactory'
      $dataProvider: '@Xima\XimaTypo3ContentAudit\Widgets\Provider\ContentStatisticsDataProvider'
      $options: '%xima_typo3_content_audit.widgets.content_statistics.options%'
    tags:
      - name: dashboard.widget
        identifier: 'contentAuditContentStatistics'
        groupNames: 'content'
        title: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.content_statistics.title'
        description: 'LLL:EXT:xima_typo3_content_audit/Resources/Private/Language/locallang.xlf:widgets.content_statistics.description'
        iconIdentifier: 'content-audit-widgets-content-statistics'
        height: 'medium'
        width: 'small'
